var name = "Dan Lavery";
var greeting = "Hi there!";
var sandwich = "Ham and Cheese";
var date = 18;
var salary = 50000;
var responses = 20;
var present = true;
var alive = true;
var retired = false;
