var me = "Dan Lavery";
var greeting = "Hi there!";
var sandwich = "Ham and Cheese";
var date = 18;
var salary = 50000;
var responses = 20;
var present = true;
var alive = true;
var retired = false;
me = "Sam Savery";
greeting = "Hey There!";
sandwich = "Spam and Cheese";
console.log(me);
console.log(greeting);
console.log(sandwich);